apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
# under linux base64 encryption - echo -n 'something' | base64
# The secret must be created before the actual deployment!
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
